### ISSUE TITLE
AnalyzerBeans using URL

### ISSUE THREAD

**Issue by phelipemaia** [datacleaner/AnalyzerBeans#68]
Is it possible to run an analyzer using the return of an URL? I have a REST service that retrieve a JSON object and I want to analyze this object.
I was wondering if I need to create a new connector or if does exist an easier way to do that.

**Comment by kaspersorensen** [comment]
So I understand it that you wish to create a _datastore_ from your URL? Not an analyzer I think? Just clarifying.

**Comment by kaspersorensen** [comment]
Duplicate of datacleaner/DataCleaner#488
